router_id: 1.1.1.1
interfaces:
  - ios_if: f2/0
    ipv4: 192.168.0.1/24
    ipv6: 2002:db8:0:1::1/64
  - ios_if: f0/0
    ipv4: 10.1.1.1/24
    ipv6: 2001:db8:0:1::1/64
    neighbor: R2
    ospfv3:
      area: 1
  - ios_if: f0/1
    ipv4: 10.2.1.1/24
    ipv6: 2001:db8:0:2::1/64
    neighbor: R3
    ospfv3:
      area: 1
  - ios_if: s1/0
    ipv4: 10.4.1.1/24
    ipv6: 2001:db8:0:4::1/64
    neighbor: R4
    ospfv3:
      area: 2
  - ios_if: s1/1
    ipv4: 10.5.1.1/24
    ipv6: 2001:db8:0:5::1/64
    neighbor: R5
    ospfv3:
      area: 2
