---
- name: Set IPv6 Unicast Routing to enabled on all devices
  hosts: routersv4
  gather_facts: false
  connection: local

  tasks:
  - name: Run ipv6 unicast-routing cli_command on IOS
    ios_config:
      lines:
        - "ipv6 unicast-routing"
