---
- name: Get IPv6 Unicast Routing informations
  hosts: routersv4
  gather_facts: false
  connection: local

  tasks:
  - name: Run show run | ipv6 unicast-routing cli_command on IOS
    ansible.netcommon.cli_command:
      command: show run
    register: result

  - name: Display result to terminal window
    debug:
      var: "'ipv6 unicast-routing' in result.stdout_lines"
