---
- name: Get IPv6 OSPF neighbor informations
  hosts: routersv4
  gather_facts: false
  connection: local

  tasks:
  - name: Run show ipv6 ospf neighbor cli_command on IOS
    ansible.netcommon.cli_command:
      command: show ipv6 ospf neighbor
    register: result

  - name: Display result to terminal window
    debug:
      var: result.stdout_lines
